AWSTemplateFormatVersion: "2010-09-09"
Description: FedRAMP Inventory Collector - Single Account Version

Parameters:
  LambdaPayloadLocation:
    Type: String
    Default: source-bucket-for-replication
    Description: 'S3 Bucket containing Lambda code'

  LambdaPayload: 
    Type: String
    Default: fedramp-inventory-lambda.zip 
    Description: Lambda zip filename

  ScheduleExpression:
    Description: Cron expression for Lambda schedule
    Type: String
    Default: cron(0 9 * * ? *)
    AllowedPattern: .+

Resources:
  InventoryCollectorLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/InventoryCollector
      RetentionInDays: 90

  IntegratedInventoryBucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: !Sub 'integrated-inventory-reports-${AWS::AccountId}' 
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldReports
            Status: Enabled
            ExpirationInDays: 2555
            NoncurrentVersionExpirationInDays: 90
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  InventoryCollectorLambdaExecuteRole:
    Type: "AWS::IAM::Role"
    DependsOn: IntegratedInventoryBucket
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns: 
        - !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
      - PolicyName: LambdaAccessRole
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: "s3:PutObject"
              Resource: !Sub 'arn:${AWS::Partition}:s3:::integrated-inventory-reports-${AWS::AccountId}/*'
            - Effect: Allow
              Action:
                - "config:SelectResourceConfig"
                - "config:DescribeConfigurationRecorders"
                - "config:DescribeConfigurationRecorderStatus"
              Resource: "*"

  InventoryCollectorLambda:
    Type: "AWS::Lambda::Function"
    DependsOn: InventoryCollectorLogGroup
    Properties:
      FunctionName: InventoryCollector
      Handler: "inventory.handler.lambda_handler"
      Runtime: "python3.11"
      Role: !GetAtt InventoryCollectorLambdaExecuteRole.Arn
      Timeout: 900
      Code:
        S3Bucket: !Ref LambdaPayloadLocation
        S3Key: !Ref LambdaPayload
      Environment:
        Variables:
          'ACCOUNT_LIST': !Sub '[{ "name": "current-account", "id": "${AWS::AccountId}" }]'
          'CROSS_ACCOUNT_ROLE_NAME': !Ref InventoryCollectorLambdaExecuteRole
          'REPORT_TARGET_BUCKET_NAME': !Ref IntegratedInventoryBucket
          'REPORT_TARGET_BUCKET_PATH': 'inventory-reports'
          'AWS_REGION': !Ref AWS::Region

  ScheduleExpressiontoTriggerInventoryCollectorLambda:
    Type: AWS::Events::Rule
    Properties: 
      Description: CloudWatch Event Rule for triggering InventoryCollector Lambda
      Name: InventoryCollector-ScheduleExpression
      ScheduleExpression: !Ref ScheduleExpression
      State: ENABLED
      Targets: 
        - Arn: !GetAtt InventoryCollectorLambda.Arn
          Id: InventoryCollectorLambda

  PermissionForEventsToInvokeLambda: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: !Ref InventoryCollectorLambda
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt ScheduleExpressiontoTriggerInventoryCollectorLambda.Arn

Outputs:
  LambdaFunctionName:
    Description: Lambda Function Name
    Value: !Ref InventoryCollectorLambda
  
  ReportBucket:
    Description: S3 Bucket for Reports
    Value: !Ref IntegratedInventoryBucket
  
  LambdaRoleArn:
    Description: Lambda Execution Role ARN
    Value: !GetAtt InventoryCollectorLambdaExecuteRole.Arn
